"""
arraybeam - antenna array analysis in Python.

The package provides three classes:

``AntennaArray``
    Arbitrary element positions, pattern by direct summation.
``UniformRectangularArray``
    Uniformly spaced planar array with FFT-accelerated pattern methods.
``UniformLinearArray``
    The single-row special case of the rectangular array.

Conventions
-----------
Positions and spacings are normalised to the wavelength; angles are in
degrees.  Patterns are computed in separable sine space
(``u = sin(azimuth)``, ``v = sin(elevation)``) with the fixed sign
convention::

    AF(u, v) = sum_i  w_i * exp(-j*2*pi*(x_i*u + y_i*v))

    w_i(beam) = exp(+j*2*pi*(x_i*sin(beam_az) + y_i*sin(beam_el))) * taper_i

Weights generated by any class are normalised to ``sum(|w|) == 1`` and are
interchangeable across every pattern method in the package.  See
:mod:`arraybeam.antenna_array` for the full discussion.

Copyright (C) 2018-2026 Zhengyu Peng <zpeng.me@gmail.com>
SPDX-License-Identifier: MIT
"""

from .antenna_array import AntennaArray
from .uniform_linear_array import UniformLinearArray
from .uniform_rectangular_array import UniformRectangularArray

__all__ = [
    "AntennaArray",
    "UniformRectangularArray",
    "UniformLinearArray",
]

__version__ = "2.0.0"
